export const data = [
  {
    title: "Handheld Folding Floor Scrubber RMM1",
    category: "Floor Scrubbers",
    image: ["./mini-ride-on-floor-scrubber-nb02/images/image-1.jpeg"],
    features: [
      "Cleaning width: 1600m/h",
      "Battery capacity: 4hr",
      "Gallon solution: 6 Gallons",
      "Recovery tank: 8 Brush",
      "drive: 15 ‘’",
      "Flexible steering",
      "Intelligent control",
      "Durable",
      "Sustainable",
    ],
    description:
      "Solution tank for holding cleaning solution. Recovery tank to collect dirty water and debris. Adjustable pressure and speed settings for customization. Maneuverability features for navigating around obstacles. Battery or power source for operation. Durable construction for longevity. Safety features such as emergency stop buttons. Easy-to-maintain design for convenience.",
  },
  {
    title: "Walk Behind Floor Scrubber NB01",
    category: "Floor Scrubbers",
    image: ["./mini-ride-on-floor-scrubber-nb02/images/image-1.jpeg"],
    features: [
      "Cleaning width: 510mm",
      "Working efficiency: 2000m/h",
      "Cleaning water tank: 45L",
      "Vacuum motor: 500W",
      "Product weight: 150Kg",
      "Working time: 3.5-4hr",
      "Squeegee width: 860mm",
      "Brush motor: 550W",
      "Squeegee tank: 50L",
      "Battery: 6EVF-103Ah*2",
    ],
    description:
      "The operation panel is simple , easy to understand and easy to use. Special water tank forward -tilt lock design makes safer working. Rotational molded brush plate cover, sturdy and durable. The dual design of liquid level switch and filter cotton protects the motor and increases its service life. Hand push battery floor scrubber, easy to operate.",
  },
  {
    title: "Mini Ride On Floor Scrubber NB02",
    category: "Floor Scrubbers",
    image: ["./mini-ride-on-floor-scrubber-nb02/images/image-1.jpeg"],
    features: [
      "Work efficiency:2000m/h",
      "Clean water tank:60L",
      "Cleaning width:510mm",
      "Vacuum motor:500W",
      "Product weight:160Kg",
      "Working time:3-3.5hr",
      "Brush motor:550W",
      "Sewage tank:75L",
      "Battery:6EVF-100AH*2",
    ],
    description:
      "Silent floor washing machine to made the needs of special occasions. Built in car charger anti-lost, anti-fall and anti-water intrusion. Lighter and more compact, suitable for smaller places. Use Fur skirt instead of traditional rubber skirt for longer service life.",
  },
  {
    title: "Walk Behind Floor Scrubber NB03",
    category: "Floor Scrubbers",
    image: ["./mini-ride-on-floor-scrubber-nb02/images/image-1.jpeg"],
    features: [
      "Work efficiency:2000m/h",
      "Clean water tank:60L",
      "Cleaning width:510mm",
      "Vacuume motor:500W",
      "Product weight:160Kg",
      "Working time:3-3.5hr",
      "Brush motor:550W",
      "Sewage tank:75L",
      "Battery:6EVF-100AH*2",
    ],
    description:
      "Silent floor washing machine to made the needs of special occasions. Built in car charger anti-lost, anti-fall and anti-water intrusion. Lighter and more compact, suitable for smaller places. Use Fur skirt instead of traditional rubber skirt for longer service life.",
  },
  {
    title: "Walk Behind Smart Mop i5",
    category: "Smart Mop",
    image: ["./mini-ride-on-floor-scrubber-nb02/images/image-2.jpeg"],
    features: [
      "Rated voltage: DC-36V",
      "Working efficiency: 800-1000 ㎡/h",
      "Brush speed: 0-350prm/min",
      "Brush motor: power 36V-120w",
      "Vacuum motor power: 36V-120W140w",
      "Detergent Tank capacity: 4L(Max)",
      "Recovery tank capacity: 6.5L(Max)",
      "Battery working hours: 8Ah-78mins",
      "12Ah-130mins",
    ],
    description:
      "The M-2 consists of two main parts: The body that contains the motors (one vacuum motor, two brush motors), cleaning solution tank, recovery tank, handle and control panel with 3 functional buttons & one power display window. The scrub deck that contains the brushes and squeegee.",
  },
];
